services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - pnpm-store:/workspace/.pnpm-store
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/myapp_dev
      - REDIS_URL=redis://redis:6379
      - PNPM_STORE_DIR=/workspace/.pnpm-store
    networks:
      - devnet
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - devnet
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - devnet
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  devnet:
    driver: bridge

volumes:
  pnpm-store:
  postgres-data:
  redis-data:
