name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: '1.22.5'
  NODE_VERSION: '22.11.0'
  PNPM_VERSION: '9.5.0'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: apps/backend/go.sum
          
      - name: Install Go tools
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.3.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Generate types
        run: pnpm run generate
        
      - name: Lint Go
        run: |
          cd apps/backend
          golangci-lint run
          
      - name: Lint Frontend
        run: pnpm run lint
        
      - name: Type check
        run: pnpm run type-check
        
      - name: Test Backend
        run: |
          cd apps/backend
          go test -v -race -coverprofile=coverage.out ./...
          
      - name: Test Frontend
        run: |
          cd apps/frontend
          pnpm test
        
      - name: Build
        run: pnpm run build

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: apps/backend/go.sum
          
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./apps/backend/...'
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
